"""empty message

Revision ID: f8ec149947e8
Revises: d7c5924a45d2
Create Date: 2021-11-04 18:07:28.114034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ec149947e8'
down_revision = 'd7c5924a45d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user', sa.Column('create_time', sa.DateTime(), nullable=False))
    op.add_column('sys_user', sa.Column('last_update_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_user', 'last_update_time')
    op.drop_column('sys_user', 'create_time')
    # ### end Alembic commands ###
