### 添加用户信息
POST http://127.0.0.1:5000/api/user
Content-Type: application/json

{
  "username": "Tom",
  "password": "123456",
  "email": "tom@example.com"
}

### 查询用户信息
GET http://127.0.0.1:5000/api/user/1
Content-Type: application/json
